version: '2'
services:
  rivertech-kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: rivertech-kafka-zookeeper
    container_name: rivertech-kafka-zookeeper
    ports:
      - "2181:2181"
    networks:
      - rivertech-network       
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  rivertech-kafka-broker:
    image: confluentinc/cp-server:7.5.0
    hostname: rivertech-kafka-broker
    container_name: rivertech-kafka-broker
    depends_on:
      - rivertech-kafka-zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    networks:
      - rivertech-network 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'rivertech-kafka-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://rivertech-kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://rivertech-schema-registry:8085
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: rivertech-kafka-broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'


  rivertech-schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: rivertech-schema-registry
    container_name: rivertech-schema-registry
    depends_on:
      - rivertech-kafka-broker
    ports:
      - "8085:8085"
    networks:
      - rivertech-network       
    environment:
      SCHEMA_REGISTRY_HOST_NAME: rivertech-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'rivertech-kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085

  rivertech-kafka-hq:
    image: tchiotludo/akhq
    restart: unless-stopped
    hostname: rivertech-kafka-hq
    container_name: rivertech-kafka-hq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            rivertech-kafka-broker:
              properties:
                bootstrap.servers: "rivertech-kafka-broker:29092"
              schema-registry:
                url: "http://rivertech-schema-registry:8085"
    ports:
      - 8080:8080
    networks:
      - rivertech-network       
    links:
      - rivertech-kafka-broker
      - rivertech-schema-registry

  rivertech-clickhouse-01:
    image: "clickhouse/clickhouse-server:23.4"
    user: "101:101"
    container_name: rivertech-clickhouse-01
    hostname: rivertech-clickhouse-01
    volumes:
      - ./fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9500:9500"
    networks:
      - rivertech-network        
    depends_on:
      - rivertech-clickhouse-keeper-01
      
  rivertech-clickhouse-02:
    image: "clickhouse/clickhouse-server:23.4"
    user: "101:101"
    container_name: rivertech-clickhouse-02
    hostname: rivertech-clickhouse-02
    volumes:
      - ./fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8124:8123"
      - "127.0.0.1:9501:9500"
    networks:
      - rivertech-network     
    depends_on:
      - rivertech-clickhouse-keeper-01

  rivertech-clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:23.4-alpine"
    user: "101:101"
    container_name: rivertech-clickhouse-keeper-01
    hostname: rivertech-clickhouse-keeper-01
    volumes:
     - ./fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "127.0.0.1:9181:9181"
    networks:
      - rivertech-network       

  rivertech-python-server:
    build: .
    container_name: rivertech-python-server
    ports:
      - "8000:8000"
    networks:
      - rivertech-network
    environment:
      KAFKA_BROKER: 'rivertech-kafka-broker:29092'
      KAFKA_TOPIC : 'staging-bets'

  rivertech-tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: rivertech-tabix
    ports:
      - "8088:80"
    environment:
      - CLICKHOUSE_HOST=rivertech-clickhouse-01
      - CLICKHOUSE_PORT=8123
    networks:
      - rivertech-network

networks:
  rivertech-network:


